[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='0x9fca1745e8e30b34fea24f52d4b4b69d08a28bf6fb97273af6e37e9b130879bd'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
